default:
    driver: mysqli
    name: sandbox
    host: "sandbox-mysql"
    user: www
    password: h0geh0ge
    port: 3306
    charset: utf8

postgres:
    driver: pdo
    dsn: "pgsql:host=sandbox-pgsql;dbname=sandbox;port=5432"
    user: www
    password: h0geh0ge

pdo:
    driver: pdo
    dsn: "mysql:host=sandbox-mysql;dbname=sandbox;charset=utf8"
    user: www
    password: h0geh0ge
